# Generated by Django 5.2.8 on 2025-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_license',
            field=models.FileField(blank=True, null=True, upload_to='media/properties/documents/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(upload_to='media/properties/main/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_proof',
            field=models.FileField(upload_to='media/properties/documents/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_deed',
            field=models.FileField(upload_to='media/properties/documents/'),
        ),
    ]
