# Generated by Django 5.2.8 on 2025-12-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0004_inquiryreply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VisitRequest",
        ),
    ]
